const CASKS_PANEL_LABEL = "Cask (software)";
const FORMULAS_PANEL_LABEL = "Formulae (command line software)";
const HEADER_HEIGHT = 54;
const MAIN_MAX_WIDTH = 680;
const PANEL_ITEM_HEIGHT = 32;
const FOOTER_HEIGHT = 35;

export {
  CASKS_PANEL_LABEL,
  FORMULAS_PANEL_LABEL,
  HEADER_HEIGHT,
  MAIN_MAX_WIDTH,
  PANEL_ITEM_HEIGHT,
  FOOTER_HEIGHT,
};
